# Generated by Django 5.1.1 on 2026-08-05 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notif_type",
                    models.CharField(
                        choices=[
                            ("APPLICATION_SUBMITTED", "Application Submitted"),
                            ("AI_VERIFIED", "AI Verification Complete"),
                            ("NADRA_VERIFIED", "NADRA Verification Complete"),
                            ("CRIMINAL_CHECKED", "Criminal Record Check Complete"),
                            ("STAFF_REVIEWED", "Staff Review Complete"),
                            ("AUTHORITY_APPROVED", "Authority Approved"),
                            ("AUTHORITY_REJECTED", "Authority Rejected"),
                            ("CHALLAN_GENERATED", "Challan Generated"),
                            ("PAYMENT_CONFIRMED", "Payment Confirmed"),
                            ("CERTIFICATE_READY", "Certificate Ready for Download"),
                            ("GENERAL", "General Notification"),
                        ],
                        default="GENERAL",
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reference_id", models.CharField(blank=True, max_length=50)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
