# Generated by Django 5.1.1 on 2026-08-12 12:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complaint_id",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SNATCHING", "Mobile / Theft Snatching"),
                            ("HARASSMENT", "Women Safety / Harassment"),
                            ("ACCIDENT", "Road Accident Assistance"),
                            ("THEFT", "Property / Vehicle Theft"),
                            ("ROBBERY", "Armed Robbery"),
                            ("OTHER", "General Citizen Complaint"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("incident_date", models.DateField(default=django.utils.timezone.now)),
                ("incident_time", models.TimeField(blank=True, null=True)),
                ("location_address", models.TextField()),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nearest_station",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("ASSIGNED", "Assigned to Officer"),
                            ("INVESTIGATION", "Under Investigation"),
                            ("RESOLVED", "Resolved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("suspect_details", models.TextField(blank=True, null=True)),
                (
                    "stolen_items_value",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("witness_info", models.TextField(blank=True, null=True)),
                ("is_helper_witness", models.BooleanField(default=False)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmergencySOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sos_id",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                (
                    "emergency_type",
                    models.CharField(
                        choices=[
                            ("CRIME_IN_PROGRESS", "Crime in Progress"),
                            ("MEDICAL_EMERGENCY", "Medical Emergency"),
                            ("ROAD_ACCIDENT", "Road Accident"),
                            ("HARASSMENT", "Harassment / Women Safety"),
                            ("SNATCHING_ROBBERY", "Snatching / Robbery"),
                            ("FIRE_SAFETY", "Fire Emergency"),
                            ("OTHER", "Other Urgent Emergency"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("location_address", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("contact_number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("DISPATCHED", "Unit Dispatched"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                ("police_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_sos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "citizen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sos_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncidentEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="incident_evidence/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Photo Evidence"),
                            ("VIDEO", "Video Clip"),
                            ("DOCUMENT", "PDF / Document"),
                        ],
                        default="IMAGE",
                        max_length=15,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "complaint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="incidents.complaint",
                    ),
                ),
                (
                    "sos",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="incidents.emergencysos",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
