# Generated by Django 5.1.1 on 2026-08-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockchainBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_index", models.IntegerField(db_index=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("previous_hash", models.CharField(max_length=64)),
                (
                    "current_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("data_hash", models.CharField(max_length=64)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CITIZEN_REGISTER", "Citizen Registered"),
                            ("PROFILE_UPDATE", "Profile Updated"),
                            ("APPLICATION_SUBMIT", "Application Submitted"),
                            ("DOCUMENT_UPLOAD", "Document Uploaded"),
                            ("AI_FACE_VERIFY", "AI Face Verification"),
                            ("NADRA_VERIFY", "NADRA Verification"),
                            ("CRIMINAL_CHECK", "Criminal Record Check"),
                            ("STAFF_REVIEW", "Staff Review / Remark"),
                            ("AUTHORITY_APPROVE", "Authority Approved"),
                            ("AUTHORITY_REJECT", "Authority Rejected"),
                            ("CHALLAN_GENERATE", "Challan Generated"),
                            ("PAYMENT_CONFIRM", "Payment Confirmed"),
                            ("CERTIFICATE_ISSUE", "Certificate Issued"),
                            ("CERTIFICATE_DOWNLOAD", "Certificate Downloaded"),
                            ("RECORD_MODIFY", "Sensitive Record Modified"),
                            ("GENESIS", "Genesis Block"),
                        ],
                        max_length=40,
                    ),
                ),
                ("record_id", models.CharField(blank=True, max_length=100)),
                ("performed_by", models.CharField(max_length=100)),
                ("nonce", models.IntegerField(default=0)),
                ("payload_json", models.TextField()),
            ],
            options={
                "verbose_name": "Blockchain Block",
                "verbose_name_plural": "Blockchain Blocks",
                "ordering": ["block_index"],
            },
        ),
    ]
