# Generated by Django 6.1 on 2026-09-19 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchainblock",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CITIZEN_REGISTER", "Citizen Registered"),
                    ("PROFILE_UPDATE", "Profile Updated"),
                    ("APPLICATION_SUBMIT", "Application Submitted"),
                    ("DOCUMENT_UPLOAD", "Document Uploaded"),
                    ("AI_FACE_VERIFY", "AI Face Verification"),
                    ("NADRA_VERIFY", "NADRA Verification"),
                    ("CRIMINAL_CHECK", "Criminal Record Check"),
                    ("STAFF_REVIEW", "Staff Review / Remark"),
                    ("AUTHORITY_APPROVE", "Authority Approved"),
                    ("AUTHORITY_REJECT", "Authority Rejected"),
                    ("CHALLAN_GENERATE", "Challan Generated"),
                    ("STAFF_FORWARD", "Staff Forwarded"),
                    ("STAFF_CONFIRM", "Staff Confirmed"),
                    ("PAYMENT_SUBMIT", "Payment Submitted"),
                    ("PAYMENT_VERIFY", "Payment Verified"),
                    ("PAYMENT_CONFIRM", "Payment Confirmed"),
                    ("CERTIFICATE_ISSUE", "Certificate Issued"),
                    ("CERTIFICATE_DOWNLOAD", "Certificate Downloaded"),
                    ("RECORD_MODIFY", "Sensitive Record Modified"),
                    ("GENESIS", "Genesis Block"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="blockchainblock",
            name="block_index",
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name="blockchainblock",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
