# Generated by Django 5.1.1 on 2026-07-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("Character Certificate", "Character Certificate"),
                            ("Tenant Verification", "Tenant Verification"),
                            ("Employee Verification", "Employee Verification"),
                            (
                                "General Police Verification",
                                "General Police Verification",
                            ),
                            ("Arms License Verification", "Arms License Verification"),
                            ("Passport Police Clearance", "Passport Police Clearance"),
                        ],
                        max_length=50,
                    ),
                ),
                ("purpose", models.TextField()),
                ("current_address", models.TextField()),
                ("nearest_station", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("FACE_VERIFIED", "Face Verified"),
                            ("CRIMINAL_CHECK", "Criminal Check"),
                            ("PAYMENT_PENDING", "Payment Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("tracking_id", models.CharField(max_length=30, unique=True)),
                ("face_confidence", models.FloatField(default=0.0)),
                ("liveness_score", models.FloatField(default=0.0)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_number", models.CharField(max_length=30, unique=True)),
                ("issue_date", models.DateField(auto_now_add=True)),
                ("validity_expiry", models.DateField()),
                ("qr_code_hash", models.CharField(max_length=100, unique=True)),
                ("digital_signature", models.TextField()),
                ("verification_url", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VALID", "Valid"),
                            ("EXPIRED", "Expired"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="VALID",
                        max_length=15,
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Challan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("challan_number", models.CharField(max_length=30, unique=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=650.0, max_digits=10),
                ),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CNIC_FRONT", "CNIC Front Side"),
                            ("CNIC_BACK", "CNIC Back Side"),
                            ("PASSPORT_PHOTO", "Passport-size Photo"),
                            ("SUPPORTING", "Supporting Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="application_docs/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
