# Generated by Django 5.1.1 on 2026-08-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("CNIC_FRONT", "CNIC Front Side"),
                    ("CNIC_BACK", "CNIC Back Side"),
                    ("PASSPORT_PHOTO", "Passport-size Photo"),
                    ("LIVE_PHOTO", "Live Captured Photo"),
                    ("SUPPORTING", "Supporting Document"),
                ],
                max_length=20,
            ),
        ),
    ]
