# Generated by Django 5.1.1 on 2026-08-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0003_alter_document_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="blockchain_transaction_hash",
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="certificate_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
