# Generated by Django 5.1.1 on 2026-08-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0004_certificate_blockchain_transaction_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("FACE_VERIFIED", "Face Verified"),
                    ("CRIMINAL_CHECK", "Criminal Check"),
                    ("CRIMINAL_CHECKED", "Criminal Checked"),
                    ("STAFF_REVIEWED", "Staff Reviewed"),
                    ("AUTHORITY_APPROVED", "Authority Approved"),
                    ("AUTHORITY_REJECTED", "Authority Rejected"),
                    ("PAYMENT_PENDING", "Payment Pending"),
                    ("PAYMENT_CONFIRMED", "Payment Confirmed"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
