# Generated by Django 5.1.1 on 2026-08-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0005_alter_application_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="applicant_province",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
