# Generated by Django 5.1.1 on 2026-07-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CriminalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnic", models.CharField(max_length=15, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "mugshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="criminal_mugshots/"
                    ),
                ),
                ("fir_number", models.CharField(blank=True, max_length=50, null=True)),
                ("crime_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "police_station",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CLEAN", "Clean"),
                            ("SUSPECTED", "Suspected"),
                            ("CRIMINAL_MATCH", "Criminal Match"),
                        ],
                        default="CLEAN",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
