# Generated by Django 5.1.1 on 2026-08-05 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_initial"),
        ("criminals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="criminalrecord",
            name="arrest_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="criminalrecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="criminalrecord",
            name="crime_severity",
            field=models.CharField(
                choices=[
                    ("NONE", "No Record"),
                    ("MINOR", "Minor Offence"),
                    ("SERIOUS", "Serious Offence"),
                    ("WANTED", "Wanted / Fugitive"),
                ],
                default="NONE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="criminalrecord",
            name="is_blacklisted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="criminalrecord",
            name="is_wanted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="criminalrecord",
            name="previous_records",
            field=models.TextField(
                blank=True, help_text="JSON list of past FIR numbers"
            ),
        ),
        migrations.AddField(
            model_name="criminalrecord",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="criminalrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="criminalrecord",
            name="cnic",
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="criminalrecord",
            name="crime_type",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="criminalrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("CLEAN", "Clean / No Record"),
                    ("SUSPECTED", "Under Suspicion"),
                    ("CRIMINAL_MATCH", "Criminal Match"),
                ],
                default="CLEAN",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CriminalCheckResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("CLEAN", "No Criminal Record"),
                            ("MINOR_RECORD", "Minor Record Found"),
                            ("SERIOUS_RECORD", "Serious Criminal Record"),
                            ("WANTED", "Wanted Person"),
                            ("PENDING", "Pending Check"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("report_summary", models.TextField()),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criminal_check",
                        to="applications.application",
                    ),
                ),
                (
                    "matched_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="criminals.criminalrecord",
                    ),
                ),
            ],
        ),
    ]
