# Generated by Django 5.1.1 on 2026-08-07 12:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applications", "0003_alter_document_document_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceVerificationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this verification report.",
                        unique=True,
                    ),
                ),
                (
                    "matched_cnic",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "matched_citizen_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "matched_father_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        default=0.0, help_text="Cosine similarity score (0.0 – 1.0)."
                    ),
                ),
                (
                    "similarity_pct",
                    models.FloatField(
                        default=0.0,
                        help_text="Similarity expressed as a percentage (0–100).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VERIFIED", "Verified ✓"),
                            ("FAILED", "Verification Failed ✗"),
                            ("NO_FACE", "No Face Detected"),
                            ("MULTIPLE_FACES", "Multiple Faces Detected"),
                            ("LOW_QUALITY", "Image Quality Too Low"),
                            ("EMBEDDING_ERROR", "Embedding Generation Error"),
                            ("DB_ERROR", "Database Error"),
                            ("STORE_NOT_READY", "Embedding Store Not Ready"),
                        ],
                        db_index=True,
                        default="FAILED",
                        max_length=30,
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("HIGH", "High (≥90%)"),
                            ("MEDIUM", "Medium (70–89%)"),
                            ("LOW", "Low (<70%)"),
                            ("NONE", "No Match"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                (
                    "threshold_used",
                    models.FloatField(
                        default=0.7,
                        help_text="Cosine similarity threshold used during this verification.",
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        default="InsightFace-ArcFace",
                        help_text="AI model used to generate embeddings.",
                        max_length=50,
                    ),
                ),
                (
                    "embedding_dim",
                    models.IntegerField(
                        default=512,
                        help_text="Dimensionality of the face embedding vector.",
                    ),
                ),
                (
                    "processing_time_ms",
                    models.FloatField(
                        default=0.0,
                        help_text="Wall-clock time in milliseconds for the full verification pipeline.",
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=50, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "blockchain_block_index",
                    models.IntegerField(
                        blank=True,
                        help_text="Index of the blockchain block recording this event.",
                        null=True,
                    ),
                ),
                (
                    "blockchain_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of the blockchain block for tamper detection.",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("verified_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        help_text="Police verification application this check relates to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="face_verifications",
                        to="applications.application",
                    ),
                ),
                (
                    "citizen",
                    models.ForeignKey(
                        blank=True,
                        help_text="The authenticated citizen who initiated verification.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="face_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Face Verification Report",
                "verbose_name_plural": "Face Verification Reports",
                "ordering": ["-verified_at"],
            },
        ),
        migrations.CreateModel(
            name="FaceVerificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("request_at", models.DateTimeField(auto_now_add=True)),
                (
                    "citizen_cnic",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "report",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="log",
                        to="face_verification.faceverificationreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Face Verification Log",
                "verbose_name_plural": "Face Verification Logs",
                "ordering": ["-request_at"],
            },
        ),
        migrations.AddIndex(
            model_name="faceverificationreport",
            index=models.Index(
                fields=["status", "verified_at"], name="face_verifi_status_664371_idx"
            ),
        ),
    ]
