# Generated by Django 6.1 on 2026-08-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("face_verification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faceverificationreport",
            name="matched_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faceverificationreport",
            name="matched_date_of_birth",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="faceverificationreport",
            name="matched_district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="faceverificationreport",
            name="matched_gender",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="faceverificationreport",
            name="matched_photo_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="faceverificationreport",
            name="matched_province",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
