# Generated by Django 5.1.1 on 2026-08-05 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applications", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NADRARecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnic", models.CharField(db_index=True, max_length=15, unique=True)),
                ("full_name", models.CharField(max_length=100)),
                ("father_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("address", models.TextField()),
                ("district", models.CharField(blank=True, max_length=100)),
                ("province", models.CharField(blank=True, max_length=100)),
                (
                    "face_image",
                    models.ImageField(blank=True, null=True, upload_to="nadra_faces/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="NADRAVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("MATCHED", "Identity Matched"),
                            ("NOT_MATCHED", "Identity Not Matched"),
                            ("NOT_FOUND", "CNIC Not Found in NADRA"),
                            ("PENDING", "Pending Verification"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("similarity_score", models.FloatField(default=0.0)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nadra_verification",
                        to="applications.application",
                    ),
                ),
                (
                    "nadra_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verifications",
                        to="nadra.nadrarecord",
                    ),
                ),
            ],
        ),
    ]
