# Generated by Django 5.1.1 on 2026-08-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nadra", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nadrarecord",
            name="face_embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
