# Generated by Django 5.1.1 on 2026-08-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="block_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="block_index",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="previous_hash",
            field=models.CharField(
                default="0000000000000000000000000000000000000000000000000000000000000000",
                max_length=64,
            ),
        ),
    ]
